# Auto-label configuration for actions/labeler
# See https://github.com/actions/labeler#match-object for syntax

documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

github:
- changed-files:
  - any-glob-to-any-file: '.github/**'
