from __future__ import annotations

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
from harness_engine import ComplianceReport, SemanticIntent
from .base import FrameworkAdapter


class AngularAdapter(FrameworkAdapter):
    """Generates Angular component code (TypeScript + HTML template) from SemanticIntent."""

    def render(self, intent: SemanticIntent) -> str:
        parts: list[str] = []
        parts.append(self._render_types(intent))
        parts.append(self._render_component_ts(intent))
        parts.append(self._render_template_html(intent))
        return "\n\n".join(parts)

    def validate(self, code: str, intent: SemanticIntent) -> ComplianceReport:
        deviations: list[dict] = []
        warnings: list[str] = []

        if "import" not in code or "Component" not in code:
            warnings.append("No Angular @Component decorator found")

        spacing_vals = set()
        if "spacing" in intent.tokens:
            spacing_vals = set(intent.tokens["spacing"].values())

        for val in spacing_vals:
            raw_pattern = "{}px".format(val)
            if raw_pattern in code:
                deviations.append({
                    "property": "spacing",
                    "found": raw_pattern,
                    "corrected_to": "token (spacing)",
                    "file": "generated",
                    "element": "template style",
                })

        return ComplianceReport(
            passed=len(deviations) == 0,
            total_elements=len(intent.components),
            deviations=deviations,
            warnings=warnings,
        )

    def _render_types(self, intent: SemanticIntent) -> str:
        lines = ["// Auto-generated by AngularAdapter", ""]
        for comp in intent.components:
            ctype = comp.get("type", "text")
            label = comp.get("label", "Component")
            if ctype == "button":
                lines.append(
                    "export interface {c}Props {{\n"
                    "  variant?: 'primary' | 'secondary' | 'ghost' | 'danger';\n"
                    "  size?: 'sm' | 'md' | 'lg';\n"
                    "  disabled?: boolean;\n"
                    "  children?: string;\n"
                    "  onClick?: () => void;\n"
                    "  dataTestid?: string;\n"
                    "}}".format(c=label)
                )
            elif ctype == "input":
                lines.append(
                    "export interface {c}Props {{\n"
                    "  placeholder?: string;\n"
                    "  value?: string;\n"
                    "  onChange?: (e: Event) => void;\n"
                    "  error?: string;\n"
                    "  dataTestid?: string;\n"
                    "}}".format(c=label)
                )
            elif ctype == "text":
                lines.append(
                    "export interface {c}Props {{\n"
                    "  variant?: 'h1' | 'h2' | 'h3' | 'h4' | 'body' | 'caption' | 'label';\n"
                    "  color?: string;\n"
                    "  align?: 'left' | 'center' | 'right';\n"
                    "}}".format(c=label)
                )
            elif ctype == "link":
                lines.append(
                    "export interface {c}Props {{\n"
                    "  href: string;\n"
                    "  target?: '_blank' | '_self';\n"
                    "  dataTestid?: string;\n"
                    "}}".format(c=label)
                )
        return "\n".join(lines)

    def _render_component_ts(self, intent: SemanticIntent) -> str:
        comps = []
        for comp in intent.components:
            ctype = comp.get("type", "text")
            label = comp.get("label", "Component")
            selector = _to_kebab(label)
            tmpl = self._component_template(ctype, label)

            comp_str = (
                "@Component({{\n"
                "  selector: '{sel}',\n"
                "  template: `{tmpl}`\n"
                "}})\n"
                "export class {c}Component {{\n"
                "  @Input() variant = 'primary';\n"
                "  @Input() size = 'md';\n"
                "  @Input() disabled = false;\n"
                "  @Input() dataTestid = '';\n"
                "  @Output() onClick = new EventEmitter<void>();\n"
                "\n"
                "  get cls(): string {{\n"
                "    const base = 'inline-flex items-center justify-center font-medium rounded focus:outline-none';\n"
                "    const vCls = this.variant === 'secondary' ? 'bg-gray-200 text-gray-900' : 'bg-blue-600 text-white';\n"
                "    const sCls = this.size === 'sm' ? 'px-3 py-1.5 text-sm' : this.size === 'lg' ? 'px-6 py-3 text-lg' : 'px-4 py-2 text-base';\n"
                "    return '${{base}} ${{vCls}} ${{sCls}}'.trim();\n"
                "  }}\n"
                "}}"
            ).format(sel=selector, c=label, tmpl=tmpl)
            comps.append(comp_str)
        return "\n\n".join(comps)

    def _component_template(self, ctype: str, label: str) -> str:
        if ctype == "button":
            return (
                "<button\n"
                "  [className]=\"cls\"\n"
                "  [disabled]=\"disabled\"\n"
                "  [attr.data-testid]=\"dataTestid\"\n"
                "  (click)=\"onClick.emit()\">\n"
                "  <ng-content></ng-content>\n"
                "</button>"
            )
        elif ctype == "input":
            return (
                "<div>\n"
                "  <input\n"
                "    className=\"block w-full rounded border border-gray-300 px-3 py-2 text-sm\"\n"
                "    [placeholder]=\"placeholder\"\n"
                "    [value]=\"value\"\n"
                "    (input)=\"onChange.emit($event)\"\n"
                "    [attr.data-testid]=\"dataTestid\"\n"
                "  />\n"
                "  <p *ngIf=\"error\" className=\"mt-1 text-xs text-red-500\">{{error}}</p>\n"
                "</div>"
            )
        elif ctype == "text":
            return "<span [className]=\"'text text--' + variant\"><ng-content></ng-content></span>"
        elif ctype == "link":
            return '<a [href]="href" [target]="target" [attr.data-testid]="dataTestid"><ng-content></ng-content></a>'
        return "<div><ng-content></ng-content></div>"

    def _render_template_html(self, intent: SemanticIntent) -> str:
        lines = ["<!-- Layout template -->"]
        if intent.layout:
            for node in intent.layout:
                lines.append(self._render_layout_node(node, intent.tokens))
        else:
            for comp in intent.components:
                sel = _to_kebab(comp.get("label", "div"))
                lines.append("<{sel}></{sel}>".format(sel=sel))
        return "\n".join(lines)

    def _render_layout_node(self, node: dict, tokens: dict) -> str:
        ltype = node.get("type", "box")
        gap = node.get("gap", "md")
        children = node.get("children", [])

        if ltype == "stack":
            cls = "flex flex-col gap-{g}".format(g=self._token_to_tailwind(gap, tokens) or "4")
        elif ltype == "inline":
            cls = "flex flex-row gap-{g} items-center".format(g=self._token_to_tailwind(gap, tokens) or "4")
        else:
            cls = "p-4"

        inner = ""
        for child in children:
            if "type" in child and child["type"] in ("stack", "inline", "box", "grid", "surface"):
                inner += "\n" + self._render_layout_node(child, tokens)
            else:
                inner += "\n<div class='layout-child'></div>"

        return '<div class="{cls}">{inner}\n</div>'.format(cls=cls, inner=inner)


def _to_kebab(name: str) -> str:
    result = []
    for i, c in enumerate(name):
        if c.isupper() and i > 0:
            result.append("-")
        result.append(c.lower())
    return "".join(result)
