from __future__ import annotations

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
from harness_engine import ComplianceReport, SemanticIntent
from .base import FrameworkAdapter


class HtmlAdapter(FrameworkAdapter):
    """Generates semantic HTML + CSS from SemanticIntent. Universal fallback."""

    def render(self, intent: SemanticIntent) -> str:
        parts: list[str] = []
        parts.append(self._render_styles(intent))
        parts.append(self._render_body(intent))
        return "\n\n".join(parts)

    def validate(self, code: str, intent: SemanticIntent) -> ComplianceReport:
        deviations: list[dict] = []
        warnings: list[str] = []

        if "<html" not in code and "<!DOCTYPE" not in code:
            warnings.append("No HTML document structure detected")

        spacing_vals = set()
        if "spacing" in intent.tokens:
            spacing_vals = set(intent.tokens["spacing"].values())

        for val in spacing_vals:
            raw_pattern = "{}px".format(val)
            if raw_pattern in code:
                deviations.append({
                    "property": "spacing",
                    "found": raw_pattern,
                    "corrected_to": "token (spacing)",
                    "file": "generated",
                    "element": "inline style",
                })

        return ComplianceReport(
            passed=len(deviations) == 0,
            total_elements=len(intent.components),
            deviations=deviations,
            warnings=warnings,
        )

    def _render_styles(self, intent: SemanticIntent) -> str:
        lines = [
            "<style>",
            "/* Auto-generated by HtmlAdapter */",
            "* { box-sizing: border-box; margin: 0; padding: 0; }",
        ]
        if "spacing" in intent.tokens:
            for k, v in intent.tokens["spacing"].items():
                lines.append(":root {{ --{k}: {v}px; }}".format(k=k.replace(".", "-"), v=v))
        if "color" in intent.tokens:
            for k, v in intent.tokens["color"].items():
                lines.append(":root {{ --color-{k}: {v}; }}".format(k=k.replace(".", "-"), v=v))
        if "radius" in intent.tokens:
            for k, v in intent.tokens["radius"].items():
                if v < 9999:
                    lines.append(":root {{ --{k}: {v}px; }}".format(k=k.replace(".", "-"), v=v))

        lines.append("")
        lines.append(".stack { display: flex; flex-direction: column; }")
        lines.append(".inline { display: flex; flex-direction: row; align-items: center; }")
        lines.append(".btn { display: inline-flex; align-items: center; justify-content: center; font-weight: 500; border: 1px solid transparent; cursor: pointer; }")
        lines.append(".btn--primary { background: var(--color-brand-primary, #2563EB); color: #fff; }")
        lines.append(".btn--secondary { background: transparent; border-color: var(--color-brand-primary, #2563EB); color: var(--color-brand-primary, #2563EB); }")
        lines.append(".input { display: block; width: 100%; border: 1px solid #d1d5db; border-radius: 4px; padding: 8px 12px; font-size: 14px; }")
        lines.append("</style>")
        return "\n".join(lines)

    def _render_body(self, intent: SemanticIntent) -> str:
        lines = ["<body>", '<div id="app">']
        if intent.layout:
            for node in intent.layout:
                lines.append(self._render_layout_node(node, intent.tokens, 2, intent))
            for comp in intent.components:
                lines.append("  " + self._render_component(comp, 0))
        else:
            for comp in intent.components:
                lines.append(self._render_component(comp, 2))
        lines.append('  </div>')
        lines.append("</body>")
        return "\n".join(lines)

    def _render_component(self, comp: dict, depth: int = 1) -> str:
        indent = "  " * depth
        ctype = comp.get("type", "text")
        label = comp.get("label", "")
        variant = comp.get("variant", "primary")
        size = comp.get("size", "md")

        if ctype == "button":
            return '{ind}<button class="btn btn--{v} btn--{s}" data-testid="{l}">{l}</button>'.format(
                ind=indent, v=variant, s=size, l=label or "Button"
            )
        elif ctype == "input":
            return '{ind}<input class="input" type="text" placeholder="{l}" />'.format(
                ind=indent, l=label or "placeholder"
            )
        elif ctype == "text":
            return '{ind}<span class="text">{l}</span>'.format(ind=indent, l=label or "Text")
        elif ctype == "link":
            return '{ind}<a class="link" href="#">{l}</a>'.format(ind=indent, l=label or "Link")
        elif ctype == "icon":
            return '{ind}<span class="icon" data-icon="{l}"><!-- icon --></span>'.format(ind=indent, l=label or "icon")
        return '{ind}<div>{l}</div>'.format(ind=indent, l=label or "")

    def _render_layout_node(self, node: dict, tokens: dict, depth: int, intent: SemanticIntent | None = None) -> str:
        indent = "  " * depth
        ltype = node.get("type", "box")
        gap = node.get("gap", "md")
        gap_val = self._token_to_tailwind(gap, tokens) or 8
        children = node.get("children", [])

        cls = ltype
        if ltype == "stack":
            cls = 'stack gap-{g}'.format(g=gap_val)
        elif ltype == "inline":
            cls = 'inline gap-{g}'.format(g=gap_val)

        inner = ""
        for child in children:
            if "type" in child and child["type"] in ("stack", "inline", "box", "grid", "surface"):
                inner += "\n" + self._render_layout_node(child, tokens, depth + 1, intent)
            else:
                child_label = child.get("label", "layout-child")
                inner += "\n{ind}<div class=\"{l}\" data-component=\"{l}\"></div>".format(ind=indent + "  ", l=child_label)

        return '{ind}<div class="{cls}">{inner}\n{ind}</div>'.format(ind=indent, cls=cls, inner=inner)
